package com.asterexcrisys.acm.types.utility;

import java.util.NoSuchElementException;

@SuppressWarnings("unused")
public record Error<V, E>(E error) implements Outcome<V, E> {

    // All necessary methods are generated by default

    public boolean isSuccess() {
        return false;
    }

    public boolean isFailure() {
        return true;
    }

    public V getValue() throws NoSuchElementException {
        throw new NoSuchElementException();
    }

    public E getError() {
        return error;
    }

    public static <V, E> Error<V, E> of(E error) {
        return new Error<>(error);
    }

}