package com.asterexcrisys.acm.types.utility;

@SuppressWarnings("unused")
public record Error<V, E>(E error) implements Outcome<V, E> {

    // All necessary methods are generated by default

    public V getValue() throws UnsupportedOperationException {
        throw new UnsupportedOperationException();
    }

    public E getError() {
        return error;
    }

    public static <V, E> Error<V, E> of(E error) {
        return new Error<>(error);
    }

}