package com.asterexcrisys.acm.types.utility;

@SuppressWarnings("unused")
public record Message(String content, boolean isSensitive) {

    // All necessary methods are generated by default

    public static Message of(String content, boolean isSensitive) {
        return new Message(content, isSensitive);
    }

}