package com.asterexcrisys.acm.types.utility;

@SuppressWarnings("unused")
public record Pair<F, S>(F first, S second) implements Tuple {

    // All necessary methods are generated by default

    public static <F, S> Pair<F, S> of(F first, S second) {
        return new Pair<>(first, second);
    }

}