package com.asterexcrisys.acm.types.utility;

@SuppressWarnings("unused")
public record Triple<F, S, T>(F first, S second, T third) implements Tuple {

    // All necessary methods are generated by default

    public static <F, S, T> Triple<F, S, T> of(F first, S second, T third) {
        return new Triple<>(first, second, third);
    }

}