package com.asterexcrisys.acm.types.utility;

@SuppressWarnings("unused")
public record Value<V, E>(V value) implements Outcome<V, E> {

    // All necessary methods are generated by default

    public V getValue() {
        return value;
    }

    public E getError() throws UnsupportedOperationException {
        throw new UnsupportedOperationException();
    }

    public static <V, E> Value<V, E> of(V value) {
        return new Value<>(value);
    }

}