package com.asterexcrisys.acm.types.utility;

import java.util.NoSuchElementException;

@SuppressWarnings("unused")
public record Value<V, E>(V value) implements Outcome<V, E> {

    // All necessary methods are generated by default

    public boolean isSuccess() {
        return true;
    }

    public boolean isFailure() {
        return false;
    }

    public V getValue() {
        return value;
    }

    public E getError() throws NoSuchElementException {
        throw new NoSuchElementException();
    }

    public static <V, E> Value<V, E> of(V value) {
        return new Value<>(value);
    }

}